config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'articles/index'
  get 'static_pages/home'
  get 'static_pages/about'
  root 'static_pages#home'
  resources :articles
  resources :users, only: [:index, :show]
  #resources :users, only: [:index], controller: 'users/users'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :articles, dependent: :destroy

  validates :username, presence: true, length: {minimum: 3, maximum: 25}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :authenticate_user!, only: [:index]
    #before_action :require_same_user, except: [:index]


    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    private

        def require_same_user
            if current_user != @user
                flash[:alert] = "You can edit or delete your profile"
                redirect_to users_path
            end
        end


end

app/views/users/index.html.erb
<h1 class="text-center mt-5 mb-5">Alphabloggers</h1>

<div class="container">
    <% @users.each do |user| %>
        <div class="card text-center">
            <div class="card-header">
                <%= user.username %>
            </div>
            <div class="card-body">
                <p class="card-text"><%= user.email %></p>
                <%= link_to 'View', user_path(user), class: 'btn btn-outline-success' %>
                <% if user.id == current_user.id %>
                    <%= link_to 'Edit', edit_user_registration_path(user), class: 'btn btn-outline-info' %>
                    <%= link_to 'Delete', user_registration_path, class: 'btn btn-outline-danger', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
                <% end %>
            </div>
            <div class="card-footer text-body-secondary">
                Joined <%= time_ago_in_words(user.created_at) %>
            </div>
        </div>
        
    <% end %>

    
</div>

app/views/users/show.html.erb
<h1></h1>

<div class="container">
    <div class="card text-center">
            <div class="card-header">
                <%= @user.username %>
            </div>
            <div class="card-body">
                <p class="card-text"><%= @user.email %></p>
                <% if current_user.id == @user.id %>
                    <%= link_to 'Edit', edit_user_registration_path(@user), class: 'btn btn-outline-success' %>
                <% end %>
                <%= link_to 'Go to all AlphaBloggers', users_path, class: 'btn btn-outline-info' %>
            </div>
            <div class="card-footer text-body-secondary">
                Joined <%= time_ago_in_words(@user.created_at) %>
            </div>
    </div>

    

    <% if @user.articles.any? %>
        <h1>Alphablogs</h1>
        <% @user.articles.each do |article| %>
            <div class="card text-center">
                <div class="card-header">
                    by <%= article.user.username %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= article.title %></h5>
                    <p class="card-text"><%= article.description %></p>
                    <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
                    <% if current_user.id == article.user.id %>
                        <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-info' %>
                        <%= link_to 'Delete', article_path(article), class: 'btn btn-outline-danger', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
                    <% end %>
                </div>
                <div class="card-footer text-body-secondary">
                    created_at <%= time_ago_in_words(article.created_at) %>, updated_at <%= time_ago_in_words(article.updated_at) %>
                </div>
            </div>
        <% end %>
    <% else %>
        <h2>No blogs yet</h2>
    <% end %>

</div>